### ISSUE TITLE
Support scaling up a node pool of size zero

### ISSUE THREAD

**Issue by mattkelly** [containership/cerebral#92]
#### Why should this feature be added?

We should support scaling up from 0 if possible. Ideally, we find a solution that works for any/multiple engines rather than putting in a workaround just for the `containership` engine.

#### How would you like the feature to work?

One approach brought up so far is to place the onus on the user to add the `containership.io/node-pool-id` label to the node selector for the ASG. This would be unfortunate because it's going against the work being done as part of #71 to eliminate this requirement on the user. It's also a workaround that's specific to Containership. Can we find a better approach?

#### What alternatives have been considered?

None yet.

#### Additional Context

N/A

**Comment by nicktate** [comment]
So, would it actually be bad to enable scaling from zero if the `containership.io/node-pool-id` was part of the selector? 

It would be custom specific logic for a given scaling engine. It isn't required, the user could still specify a more arbitrary selector for their ASG, it would just be documented that this comes with the caveat of not being able to scale from 0. If you do however, provide this key that the containership scaling engine looks for, then it would allow the user to scale from 0. 

I cannot think of any other real way to get around it. The only alternative in a more generic sense, would be to have some generic selector for "cloud specific ASG constructs" in addition to a node selector as part of the ASG. You could think of this similar to how the Kubernetes cluster autoscaler can dynamically select ASGs from AWS based on a cloud label set on them. I think abstracting this across all providers would be difficult though, this sort of logic may just have to be custom per scaling engine. 

Thoughts @mattkelly?

**Comment by normanjoyner** [comment]
Documenting a use case from @nicktate in support of this feature:
> Consider you have Kubernetes Jobs that you periodically run. Other than that, you don’t need to use the node pool at all. In an ideal world, it would scale to 0 when you are not running a job. Then one would be scheduled, and it would scale up to make room to run the workload.

**Comment by normanjoyner** [comment]
As I’ve been thinking about how to address this, I figured I would document my current thought process for posterity.

In my mind, our current set of metrics backends should **not** logically support scaling up from zero as their scale up policy can **never** be triggered. That being said, I think a new set of available metrics can be added to the Kubernetes metrics backend to support this functionality. More specifically, a new metric such as `pod_unschedulable` could be introduced to respond to such events, satisfying the use case outlined above. I do fundamentally believe that regardless of if the workload is a short-running process such as a Job, or a long-running one such as deployment, the use case is validated, and fulfilled by adding node resource capacity on-demand to satisfy pod scheduling.

From an `AutoscalingPolicy` perspective, this may look like:
```
apiVersion: cerebral.containership.io/v1alpha1
kind: AutoscalingPolicy
metadata:
  name: pod-unschedulable-example-policy
spec:
  metric: pod_unschedulable
  metricConfiguration: {}
  metricsBackend: kubernetes
  pollInterval: 15
  samplePeriod: 15
  scalingPolicy:
    scaleUp:
      adjustmentType: absolute
      adjustmentValue: 1
      comparisonOperator: ‘>‘
      threshold: 0
```
*Note: a `scaleDown` policy would not be necessary for this Autoscaling Policy*

This approach does not come without a unique set of challenges. If the user had multiple node pools with such an Autoscaling Policy added, they would all in theory trigger, causing each node pool to scale up when only one node may be necessary. Additionally, there is no guarantee that the provisioned node will have the correct resource capacity to accommodate the pod as the Autoscaling Group, nor the Autoscaling Engine have a concept of resources. Furthermore, the provisioned node may not have the correct labels, or tolerate the correct taints to satisfy pod placement. 

The best way I can think to work around the latter issue is to allow the user to duplicate node pool labels / taints in the `metricConfiguration` such that when attempting to place a pod, scheduling is essentially run against these values, instead of actual node labels / taints. For example:
```
apiVersion: cerebral.containership.io/v1alpha1
kind: AutoscalingPolicy
metadata:
  name: pod-unschedulable-example-policy
spec:
  metric: pod_unschedulable
  metricConfiguration:
    labels:
      unique-label-key: unique-label-value
  metricsBackend: kubernetes
  pollInterval: 15
  samplePeriod: 15
  scalingPolicy:
    scaleUp:
      adjustmentType: absolute
      adjustmentValue: 1
      comparisonOperator: ‘>‘
      thre
```

Now, when an unschedulable pod has unique affinity options, the proper node pool can be selected by mimicking Kubernetes scheduling. If no node pools match the affinity options, or the matching node pools have taints that are not tolerated by the pod, the node pool will not scale. Note that since each node pool still has an associated `pod_unschedulable` Autoscaling Policy, any matching node pools would scale up, meaning multiple nodes can still be added in response to an unschedulable pod. I am unsure how to solve this problem without a single AutoscalingPolicy targeting the entire cluster. I will also readily admit that this duplication of work for the user is less than ideal.
